runners:
 local-runner:
  image: public.ecr.aws/y2s4f3y9/ubuntu-generic:latest
jobs:   
 hello-world:
  resource_spec: micro
  runner: local-runner
  current_working_directory: ~/
  input: 
   artifact: 
    - id_rsa
  steps:
   - run:
      name: Open connection to pi
      command: |
       eval `ssh-agent -s`
       chmod 600 ./id_rsa
       ssh-add ./id_rsa
       chmod 777 ./raspberrypi.expect
       ./raspberrypi.expect
      
workflows:
 hello-world-workflow:
  jobs:
   - hello-world
